### ISSUE TITLE
Test working for ver 1.10.26 and some newbie question on docker 

### ISSUE THREAD

**Issue by believeitcode** [koenvervloesem/rasa-docker-arm#5]
Hi , Thanks for building the arm images for Rasa on RPi 4 , i tested with ver 1.10.26 the rasa core server worked fine but i have yet test the actions server for it . I have question regarding to docker as i'm quite new to docker. 

Question 

1)  What command line or modification to docker compose file do we need to start actions server at port 5055 .

2) Will your image work for rasa 2.x ver  ? 

Thanks

**Comment by believeitcode** [comment]
Btw there is some error occur when building the docker image which i think it don't affect much 
![Error](https://user-images.githubusercontent.com/40289508/123128256-945c2780-d47d-11eb-9d0a-abfb24ab7678.png)

**Comment by koenvervloesem** [comment]
Hi,

1. You should consult the Rasa documentation for that.
2. I haven't found the time yet to build a Docker image for Rasa 2.x versions (see https://github.com/koenvervloesem/rasa-docker-arm/issues/2).
3. Yes, I have been seeing this error for a couple of releases now, but it doesn't seem to impact functionality.

**Comment by koenvervloesem** [comment]
Just for reference, this is the Docker Compose file I'm using to test the releases of my Docker images:

```yaml
version: '3.7'
services:
  rasa:
    image: rasa:1.10.26
    expose:
      - 5005
    ports:
      - 5005:5005
    volumes:
      - ./app:/app
    command:
      - run
      - --cors
      - "*"
```
